# Interesting themes:
# - https://github.com/jmooring/hugo-stork?ref=hugothemesfree.com


################################# Default configuration ###################

# provide your domain here
baseURL = "localhost"

# theme
theme = "dot"

# site title
title = "Ilnoime"

# Languages
defaultContentLanguage = "fr"
disableLanguages = ["en"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################

[params]
# logo is for all page
logo = ""

# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""

# when logo is empty, it will show your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#8c2ee4"
body_color = "#1f1f1a"
text_color = "#888888"
text_color_dark = "#a0a0a0"
white_color = "#333"
light_color = "#555"

# font family
font_family = "Anek Latin" # Choose font family from : https://fonts.google.com/


############################## Social links ##############################

[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
name = "Facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
name = "Linkedin"
link = "#"

################################ English Language ######################

[Languages.en]
languageName = "English"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2021 a Hugo theme by [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.en.params.banner]
title = "The world of Ilnoime"
subtitle = "A post-apocalyptic world."
bg_image = "images/banner.jpg"
placeholder = "Search the encyclopedia"

################## English navigation #################

[[Languages.en.menu.main]]
name = "Home"
url = ""
weight = 1

[[Languages.en.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "contact/"
weight = 3

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing/"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features/"
  weight = 3


################################### French Language ######################

[Languages.fr]
languageName = "Français"
languageCode = "fr-fr"
weight = 2
copyright = "Copyright &copy; 2021 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.fr.params.banner]
title = "Comment pouvons nous aider?"
subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
bg_image = "images/banner.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

################## French navigation #################

[[Languages.fr.menu.main]]
name = "nature"
url = "nature/"
weight = 1
hasChildren = true

	[[Languages.fr.menu.main]]
	parent="nature"
	name = "Géographie"
	url = "geography/"
	weight = 1

	[[Languages.fr.menu.main]]
	parent="nature"
	name = "Espèces, Races, Ethnicithés"
	url = "species/"
	weight = 2

	[[Languages.fr.menu.main]]
	parent="nature"
	name = "Créatures"
	url = "creatures/"
	weight = 3

[[Languages.fr.menu.main]]
name = "Culture"
url = "culture/"
weight = 2
hasChildren = true

[[Languages.fr.menu.main]]
name = "Géopolitique"
url = "geopolitics/"
weight = 3
hasChildren = true

[[Languages.fr.menu.main]]
name = "Personnages"
url = "characters/"
weight = 4
hasChildren = true

[[Languages.fr.menu.main]]
name = "Annexes"
url = "appendix/"
weight = 5
